name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: python installation
        uses: actions/setup-python@v4
        with: 
           python-version: '3.11'
      - name: install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install PyYAML
      - name: generate feed
        run: python feed.py
      - name: git commit
        run: |
            git config username github-actions
            git config password github-actions@github.com
            git add .
            git commit -m "modify changes"
            git push
